version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
  
  # nginx:
  #   container_name: nginx
  #   build: ./requirements/nginx/.
  #   # ports:
  #   #   - "443:443"
  #   # depends_on:
  #   #   - wordpress
  #   volumes:
  #     - ./requirements/nginx/conf/:/etc/nginx/conf.d
  #     # - ./requirements/nginx/tools:/etc/nginx/ssl
  #   restart: always

volumes:
  mariadb_data:
    driver: local