version: '3.8'

services:
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb/.
        init: true
        env_file:
            - .env
        networks:
            - inception
        volumes:
            - mdb-vol:/var/lib/mysql
        restart: always

    nginx:
        container_name: nginx
        build: ./requirements/nginx/.
        init: true
        ports:
        - "443:443"
        depends_on:
        - wordpress
        networks:
        - inception
        volumes:
            - ./requirements/nginx/conf/:/etc/nginx/conf.d
            - ./requirements/tools/:/etc/nginx/ssl
            - wp-vol:/var/www/html
        restart: always
  
    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress/.
        init: true
        networks:
            - inception
        volumes:
            - wp-vol:/var/www/html
        env_file:
            - .env
        restart: always

    redis:
        container_name: redis
        build: ./requirements/bonus/redis/.
        init: true
        ports:
            - "6379:6379"
        networks:
            - inception
        restart: always
    
    adminer:
        container_name: adminer
        build: ./requirements/bonus/adminer/.
        init: true
        ports:
            - "8080:8080"
        depends_on:
            - mariadb
        networks:
            - inception
        restart: always


networks:
    inception:
        name: inception

volumes:
    mdb-vol:
        name: mdb-vol
        driver: local
        driver_opts:
            device: /home/oubelhaj/data/mariadb
            o: bind
            type: none
    wp-vol:
        name: wp-vol
        driver: local
        driver_opts:
            device: /home/oubelhaj/data/wordpress
            o: bind
            type: none