version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mdb-vol:/var/lib/mysql
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/conf.d
      - ./requirements/tools/:/etc/nginx/ssl
      # - ./requirements/nginx/fol/:/etc/www/html
      - wp-vol:/var/www/html
    restart: always
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    networks:
      - inception
    volumes:
      - wp-vol:/var/www/html
    env_file:
      - .env
    restart: always

networks:
  inception:
    name: inception

volumes:
  mdb-vol:
    name: mdb-vol
    driver: local
    driver_opts:
      device: /home/oubelhaj/data/mariadb
      o: bind
      type: none
  wp-vol:
    name: wp-vol
    driver: local
    driver_opts:
      device: /home/oubelhaj/data/wordpress
      o: bind
      type: none